### ISSUE TITLE
Test - DB Models of User

### ISSUE THREAD

**Issue by scattm** [ViiSiX/DanceCats#61]
Add test for DB models of User and related. Include:
- User
- AllowedUser
  **Target: 85% coverage**

**Comment by caohhung** [comment]
Test your new commit with `git diff HEAD~1 | flake8 --diff`

**Comment by scattm** [comment]
Ops, nothing happen.

**Comment by caohhung** [comment]
Test cases for Models.User:
 + should_add_new_users
 + should_not_add_existed_user
 + should_set_last_login
 + unregistered_user_login_first_time_should_be_added (both case allowed_email & disallowed_email)
+ should_set_last_update

**Comment by scattm** [comment]
Changed issue scope.

**Comment by caohhung** [comment]
Please kindly ignore this issue. I won't do it anymore until I know more about schedules and jobs
