### ISSUE TITLE
User & Role - Adding features and improving model

### ISSUE THREAD

**Issue by scattm** [ViiSiX/DanceCats#81]
As the result of User Model unit testing in #61. We need to add more features and improve the User Model. Those items list below just for note, we will add more issues for them later.

**Feature**:
- Disable user
- Delete user
- Change email
- Change password #72 
- User roles (Execute/View/Edit) #71 

**Improve**:
- Process of duplicate
- More user states
- Password expiration

**Comment by caohhung** [comment]
+ User roles (Execute/View/Edit)
 + Change password
